name: FireworkShow
main: DavyCraft648\FireworkShow\FireworkShow
version: 0.1.0
api: 5.34.0
author: DavyCraft648
description: Add a fireworks show to your PocketMine server
website: https://github.com/DavyCraft648/FireworkShow
load: POSTWORLD
permissions:
  fireworkshow.command.fireworkshow:
    description: Allows the use of the /fireworkshow command
    default: op